# Permalinks
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://valentinabojan.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Valentina Bojan
  email:             bojan.valentinacamelia@gmail.com
  avatar:            https://gravatar.com/userimage/70327762/786d00eea1f72ee727e667326d0be3c9.jpeg

plugins: [jekyll-paginate]