# Permalinks
permalink:           pretty

# Setup
title:               The Jar of Bits
tagline:             'Mind what you have learned. Save you it can.'
description:         'Here, find stranger bits, you will. Forget to always pass on what you have learned, do not.'
github:
  repo:              https://github.com/valentinabojan/valentinabojan.github.io
baseurl:             ''
paginate:            5

excerpt_separator: '<!--- excerpt -->'

# About/contact
author:
  name:              Valentina Bojan
  email:             bojan.valentinacamelia@gmail.com
  github:            https://github.com/valentinabojan
  linkedin:          https://www.linkedin.com/in/valentina-camelia-bojan-55560b99/
  avatar:            https://gravatar.com/userimage/70327762/3680c659af74a88706d984a87a97c04f.jpg?size=160
  avatar1:           https://en.gravatar.com/userimage/70327762/c22f7d8b4cdf025474bad9cbf7ed9119.jpg?size=128

# Google Analytics
google_analytics: UA-124157958-1

# Disqus
disqus-id: valentinabojan-github-io
page-path: valentinabojan.github.io

plugins:
  - jekyll-paginate
  - jekyll-seo-tag